from typing import Protocol, Optional, Tuple, Any

class IFrameCaptureInterface(Protocol):
    """
    Allowing different capture strategies to be
    used interchangeably in a factory pattern.
    """

    async def start_capture(self, source: Optional[str] = None) -> None: ...

    async def stop_async(self, wait_timeout: float = 1.0) -> None: ...

    def stop(self) -> None: ...

    def reset_for_new_video(self) -> None: ...

    def get_latest_frame(self) -> Tuple[Optional[Any], int, Optional[float]]: ...

    def get_latest_frame_gpu(self): ...

    def get_frame_data(self): ...

    def get_progress(self) -> Optional[float]: ...